---
- hosts: controller
  become: false
  gather_facts: false
  pre_tasks:
    - set_fact: fact_controller_user="{{ lookup('env','USER') }}"
    - set_fact: fact_controller_home="{{ lookup('env','HOME') }}"

    - debug: var=fact_controller_user
    - debug: var=fact_controller_home

  tasks:

  - name: Load a variable file based on the OS type, or a default if not found. Using free-form to specify the file.
    include_vars: "{{ item }}"
    with_first_found:
      - "{{ ansible_distribution }}.yml"
      - "{{ ansible_os_family }}.yml"
      - "vars/project_customizations.yml"

  - name: "template group_vars/all/customize_project.yml"
    template: src=templates/group_vars/all/customize_project.yml.j2 dest=group_vars/all/customize_project.yml

