---
- hosts: all
  become: false
  gather_facts: false
  pre_tasks:
    - set_fact: fact_controller_user="{{ lookup('env','USER') }}"
    - set_fact: fact_controller_home="{{ lookup('env','HOME') }}"

    - debug: var=fact_controller_user
    - debug: var=fact_controller_home


- include: controller.yml
- include: production.yml
- include: staging.yml
- include: development.yml
