---
# file: group_vars/all/create_project.yml

create_project_testing         : False
create_project_accept_hostkey  : True

create_project_license_year    : '2016'
create_project_author          : 'Firstname Lastname'
create_project_license         : 'mit'

# used to create paths
#
#create_projects_root_dir       : '~/projects' # to incorporate at a later date
create_project_parent_dir      : 'parc'  # a useful place to store things we want to keep out of the projects (public) repo.

# used to create paths and for repository naming
#
create_project_project_type    : 'ansible'      # 'ansible'     # 'development' # 'ansible'
create_project_project_subtype : 'role'         # 'development' # 'project'     # 'project'
create_project_project_name    : 'kvm'   # 'docs'        # 'docs'        # 'automa'

# then long name of the repository we are developing
create_project_repo_long_name  : '{{ create_project_project_type }}-{{ create_project_project_subtype }}-{{ create_project_project_name }}'

# git

create_project_git_user        : 'cjsteel'
create_project_git_server      : 'github.com'
create_project_shared_repo_url : 'git@{{ create_project_git_server }}:{{ create_project_git_user }}/{{ create_project_repo_long_name }}.git'
#create_project_shared_repo_url : 'git@github.com:cjsteel/ansible-project-automa.git'

# controller

create_project_controller_user : '{{ fact_controller_user }}'
create_project_controller_group: '{{ create_project_controller_user }}'
create_project_controller_home : '{{ fact_controller_home }}'

create_project_user            : '{{ create_project_controller_user }}' # 'mary'
create_project_group           : '{{ create_project_controller_group }}'
create_project_home            : '{{ create_project_controller_home }}'
create_project_mode            : '0755'

## Production
#
# Required by "TASK [development : Execute 'git remote add production' in the development repo"

production_host : 'localhost'

production_user  : '{{ create_project_user }}'
production_group : '{{ create_project_group }}'
production_home  : '{{ create_project_home }}'
production_mode  : '{{ create_project_mode }}'

production_projects_root     : '{{ production_home }}/projects'
production_project_name      : '{{ create_project_project_name }}'
production_project_root_path : '{{ production_projects_root }}/{{ create_project_parent_dir }}/{{ production_project_name }}'

production_repository     : '{{ production_project_root_path }}/prod-repo'
production_repository_url : '{{ production_user }}@{{ production_host }}:{{ production_repository }}'

production_server_dir     : '{{ production_project_root_path}}/prod-srv'

## Staging
#
# required by "TASK [development : template development repos .git/hooks/post-commit]"

staging_host : 'localhost'

staging_user            : '{{ create_project_user }}' 
staging_group           : '{{ create_project_user }}'
staging_home            : '{{ create_project_home }}'
staging_mode            : '{{ create_project_mode }}'

staging_projects_root     : '{{ staging_home }}/projects'
staging_project_name      : '{{ create_project_project_name }}'
staging_project_root_path : '{{ staging_projects_root }}/{{ create_project_parent_dir }}/{{ staging_project_name }}'

staging_server_dir : '{{ staging_project_root_path}}/stage-srv'

## Development
#

development_origin_master_repository: '{{ create_project_shared_repo_url }}'

development_host : 'localhost'

development_user  : '{{ create_project_user }}' 
development_group : '{{ create_project_user }}'
development_home  : '{{ create_project_home }}'
development_mode  : '{{ create_project_mode }}'

development_projects_root     : '{{ development_home }}/projects'
development_project_name      : '{{ create_project_project_name }}'
development_project_root_path : '{{ development_projects_root }}/{{ create_project_parent_dir }}/{{ development_project_name }}'

development_server_dir : '{{ development_project_root_path}}/stage-srv'
development_repository : '{{ development_project_root_path }}/dev-repo'


