---
# tasks file for ansible-role-staging

- name: "ensure for staging server directory"
  become: false
  file:
    state='directory'
    path='{{ staging_server_dir }}'
    owner='{{ staging_user }}'
    group='{{ staging_group }}'
    mode='{{ staging_mode }}'
#  when: ansible_distribution == "CentOS"

